version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync . s3://joybitinfra-static-prod-451124812411-us-west-1   --delete
      - echo Creating CloudFront Invalidation...
      - aws cloudfront create-invalidation --distribution-id E2OYX05PPJPK5L --paths "/*"

artifacts:
  files:
    - '**/*'
