version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync . s3://$BUCKET_NAME --delete
      - echo Creating CloudFront Invalidation...
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
