AWSTemplateFormatVersion: '2010-09-09'
Description: Joy Bit Infra - Static Website with CodePipeline - Infra Stack

Parameters:
  Environment:
    Type: String
    Default: prod

  WebACLArn:
    Type: String
    Description: Enter WAF WebACL ARN from us-east-1

Resources:

  ###################################################
  # S3 BUCKET
  ###################################################

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "joybitinfra-static-${Environment}-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: project
          Value: static-website-codepipeline
        - Key: company
          Value: joybitinfra
        - Key: environment
          Value: !Ref Environment
        - Key: owner
          Value: jhanikiraman
        - Key: managedby
          Value: cloudformation
        - Key: costcenter
          Value: onboarding-project
        - Key: region
          Value: !Ref AWS::Region

  ###################################################
  # CLOUDFRONT OAC
  ###################################################

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "joybitinfra-oac-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ###################################################
  # CLOUDFRONT DISTRIBUTION
  ###################################################

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        WebACLId: !Ref WebACLArn
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100
      Tags:
        - Key: project
          Value: static-website-codepipeline
        - Key: company
          Value: joybitinfra
        - Key: environment
          Value: !Ref Environment
        - Key: owner
          Value: jhanikiraman
        - Key: managedby
          Value: cloudformation

  ###################################################
  # BUCKET POLICY
  ###################################################

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${WebsiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
    Export:
      Name: joybitinfra-bucket-name

  DistributionId:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: joybitinfra-distribution-id

  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
